### ISSUE TITLE
请问可以出一个自定义模板格式的版本吗？

### ISSUE THREAD

**Issue by pannnkee** [loveinsky100/goanno#1]
eg:
// 查询筛选后的数据
// @param sids 筛选条件
// @return data 所有数据
// @return count 数量
// @return err 错误信息

**Comment by loveinsky100** [comment]
最近比较忙，计划是在开发中==

**Comment by pannnkee** [comment]
好，期待用上新的注释插件，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "loveinsky100/goanno"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 下午3:14
收件人:&nbsp;"loveinsky100/goanno"<goanno@noreply.github.com&gt;;
抄送:&nbsp;"pannnkee"<522240909@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [loveinsky100/goanno] 请问可以出一个自定义模板格式的版本吗？ (#1)





 
最近比较忙，计划是在开发中==

**Comment by loveinsky100** [comment]
现在支持自定义模版了，已经推送到jetbrains了。预计1天后可以下载到更新，也可以直接使用release包通过本地安装更新。
https://github.com/loveinsky100/goanno/releases/tag/2.0.0

**Comment by loveinsky100** [comment]
issue我关闭了，如果有问题可以继续提出，多谢

**Comment by pannnkee** [comment]
已经更新，测试过了很好用，谢谢支持




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "loveinsky100/goanno"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 晚上10:11
收件人:&nbsp;"loveinsky100/goanno"<goanno@noreply.github.com&gt;;
抄送:&nbsp;"pannnkee"<522240909@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [loveinsky100/goanno] 请问可以出一个自定义模板格式的版本吗？ (#1)





 
issue我关闭了，如果有问题可以继续提出，多谢
