### ISSUE TITLE
在ubuntu18.04 环境上，安装插件后，在tools没有看到Goanno的setting

### ISSUE THREAD

**Issue by RavenHide** [loveinsky100/goanno#12]
os：ubuntu18.04
goland Version：2021.01
安装插件后，在tools没有看到Goanno的setting
![image](https://user-images.githubusercontent.com/19531134/118772729-a4994980-b8b6-11eb-8bdb-31d707585c6b.png)

**Comment by loveinsky100** [comment]
不实在设置的tool里，在菜单的tools里，参考截图，手里没有ubuntu环境，不了解菜单zai na在哪，等装个虚拟机看下
![image](https://user-images.githubusercontent.com/18205561/119098688-a8f56c00-ba48-11eb-87b8-be5209057d93.png)

**Comment by hentai8** [comment]
遇到了同样的问题，ubuntu下goland2021.2菜单栏上没有tools，因此找不到goanno settings。

**Comment by loveinsky100** [comment]
邮件已收到。徐

**Comment by loveinsky100** [comment]
![image](https://user-images.githubusercontent.com/18205561/151113146-1ca46fac-cc1c-47c5-b098-6b53d0212317.png)
在这里 不是设置里面
