### ISSUE TITLE
支持其它类型名称(如结构体)

### ISSUE THREAD

**Issue by GuiBin2013** [loveinsky100/goanno#13]
会考虑支持提取其他类型的名称，例如struct，interface吗？

lint要求公开类型要写注释，以 // {name} xxx 开头

如{struct_name} {interface_name} 

如果插件是用go写的，我会直接自己改，无奈java实在太烂了。。。

thx

**Comment by loveinsky100** [comment]
插件只能用java开发==，这块我抽空加上，如果你有空也可以push一个mr上来😄

**Comment by loveinsky100** [comment]
最近工作比较忙 没什么时候维护==

**Comment by GuiBin2013** [comment]
@loveinsky100 
没写过java，爱莫能助啊==

**Comment by loveinsky100** [comment]
已支持，正在测试，预计本周推到插件市场

**Comment by loveinsky100** [comment]
已开发完成，插件市场预计两天内审核完成可以下载，可以通过这个地址下载进行本地安装https://github.com/loveinsky100/goanno/releases/tag/v3.0.0
