### ISSUE TITLE
更新插件生成注释问题

### ISSUE THREAD

**Issue by lyxlk** [loveinsky100/goanno#17]
![image](https://user-images.githubusercontent.com/10336809/131086518-d6581b70-683f-4374-b27f-054b04dd09f9.png)

更新插件后，为啥我生成的注释是这样的，难看屎了~

在我更新插件之前，还是如下这样的，多清爽
![image](https://user-images.githubusercontent.com/10336809/131086739-485a4bf1-38d1-458e-9c28-5aaed46f3709.png)

**Comment by loveinsky100** [comment]
抱歉，你可以通过Tools/Goanno Setting调整模板格式





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: linkai ***@***.***&gt;
发送时间: 2021年8月27日 15:07
收件人: loveinsky100/goanno ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[loveinsky100/goanno] 更新插件生成注释问题 (#17)





 

 
更新插件后，为啥我生成的注释是这样的，难看屎了~
 
在我更新插件之前，还是如下这样的，多清爽
