### ISSUE TITLE
Edit box black

### ISSUE THREAD

**Issue by SliverHorn** [loveinsky100/goanno#19]
Edit box black
![image](https://user-images.githubusercontent.com/45428434/132462095-4e0be839-57b5-459f-bbe7-33c6ad6ba10e.png)
Need to be checked to display my custom text
![image](https://user-images.githubusercontent.com/45428434/132462070-e3291104-e098-4f3a-941c-c9ff9eafd0f4.png)
Please fix it.

**Comment by SliverHorn** [comment]
The version I use is 3.0.0

**Comment by loveinsky100** [comment]
👌，I will fix this problem as soon as possible

**Comment by loveinsky100** [comment]
https://github.com/loveinsky100/goanno/commit/36c637c8a5ab914993f2f192ace1fd99c1912d87#diff-41fb3b2a8cdd520427a3dfd26eca59899f12a8bc12be453377c969babdcf9df7
https://github.com/loveinsky100/goanno/releases/tag/3.0.1
