### ISSUE TITLE
In Go comments for doc should be // not /** **/

### ISSUE THREAD

**Issue by aukgit** [loveinsky100/goanno#2]
Hello ,

Nice to see the great package, everything is good with few exceptions only.

In Go comments for doc should be `//` not `/** **/`

Current:

![image](https://user-images.githubusercontent.com/4561204/100249641-fc3da480-2f66-11eb-8b0e-43f37cb3bdb0.png)

```go

/**
 * @Description:
 * @receiver contents
 * @param param1
 * @param param2
 * @return *[]string
 */ 
func (contents *Contents) extractToStrings(param1 int, param2 string) *[]string {
}
```

A great comment may look like this 

![image](https://user-images.githubusercontent.com/4561204/100249771-242d0800-2f67-11eb-8508-37fbe68a5025.png)

```go
// extractToStrings @return *[]string
//
// @Description:
//
// @receiver contents :
//
// @param param1:
//
// @param param2:
//
// @Conditional Notes:
//   - Condition 1 : returns ....
//   - Condition 2 : returns ....
func (contents *Contents) extractToStrings(param1 int, param2 string) *[]string {
}
```

## Reference

- [Godoc](https://blog.golang.org/godoc)

**Comment by loveinsky100** [comment]
Hi, I release version "2.0.0" now you can edit you custom template. You can download from jetbrains within 1 day. Also, you can download goanno.jar from "https://github.com/loveinsky100/goanno/releases/tag/2.0.0" then install from disk.
![image](https://user-images.githubusercontent.com/18205561/101173964-35b89300-367e-11eb-973e-500a5ad5cd7d.png)
