### ISSUE TITLE
golang: type BootstrapList []*ent.Bootstrap going to the other case

### ISSUE THREAD

**Issue by godcong** [loveinsky100/goanno#20]
```go
type BootstrapList []*ent.Bootstrap
```

want
```
//BootstrapList xxx
type BootstrapList []*ent.Bootstrap
```

get
```
//
type BootstrapList []*ent.Bootstrap
```

ps:I hope the comments generated by default can be checked by the code inspection tool. (like: golink,revive)
but,some templates need to be modified.

**Comment by loveinsky100** [comment]
type去定义一个新类型，目前模版逻辑未识别这种语句，走了Other的模版，所以输出 “//”。对于这种语句或者其他的比如const，var等语句有在考虑是否支持，因为目前模版分类非常多了，对于过多的配置反而不易使用。
对于默认模版的golint检测，我这边目前的确遇到了一些问题，后续会调整默认模版。

**Comment by godcong** [comment]
如何添加：定义一个新类型？

**Comment by loveinsky100** [comment]
https://github.com/loveinsky100/goanno/issues/39 会在下个版本支持
