### ISSUE TITLE
希望新增换行符功能 

### ISSUE THREAD

**Issue by a67793581** [loveinsky100/goanno#23]
目前使用mac环境
配置
// ${function_name} 
//
// @Description: ${todo}
//
// @receiver ${receiver_name_type} ""\n
//
// @param ${param_name_type} ""
//
// @return ${ret_name_type} ""
上面的配置\n并不会换行

**Comment by loveinsky100** [comment]
了解 下个版本会支持上

**Comment by loveinsky100** [comment]
https://github.com/loveinsky100/goanno/commit/4df7194a639b0ea1c345c9f31fb432c49b4a7c41
