### ISSUE TITLE
希望增加自动生成时间功能

### ISSUE THREAD

**Issue by liwentaogit** [loveinsky100/goanno#28]
设置Normal method的template，要如何设置才自动生成加注释时间呀。如下图
<img width="289" alt="截屏2022-01-19 下午4 11 23" src="https://user-images.githubusercontent.com/83341243/150090085-ae1718e9-2ff8-43ad-98f5-0b256914aa7b.png">

**Comment by loveinsky100** [comment]
![image](https://user-images.githubusercontent.com/18205561/151113439-7f470d99-fc35-4a18-8afe-b755b894540a.png)
![Uploading image.png…]()
