### ISSUE TITLE
Tools 里没有 Goanno Setting

### ISSUE THREAD

**Issue by fishtailstudio** [loveinsky100/goanno#29]
我想要设置注释模板，但是我在 Preferences - Tools 里没有发现 “Goanno Setting”
GoLand版本: 2021.3.3
OS: MacOS Monterey 12.2.1
<img width="1203" alt="WX20220228-161749@2x" src="https://user-images.githubusercontent.com/32082810/155948419-1c01e7b0-877e-4644-a298-ac3376cf7fea.png">

**Comment by loveinsky100** [comment]
邮件已收到。徐

**Comment by fishtailstudio** [comment]
got it, thanks.
