### ISSUE TITLE
可以支持添加函数名称吗？满足golint对导出函数注释的检查

### ISSUE THREAD

**Issue by flead** [loveinsky100/goanno#3]
模板
//
//  ${functionname} .
// @Description:
//

结果：
//
// GetInfo
// @Description:
//
func GetInfo(c *gin.Context) {

**Comment by loveinsky100** [comment]
可以加一下

**Comment by flead** [comment]
期待大佬加一下 ，现在腾讯 阿里的checklistzhong都有这个，手工写注释有点慢，他们一定用得着。

**Comment by shrek7** [comment]
同样期待

**Comment by loveinsky100** [comment]
已支持，可以从 https://github.com/loveinsky100/goanno/releases/tag/2.0.1 下载release包，从本地安装，也可以通过插件市场安装（已上传，但审核需要1天左右）
![goanno_function_name](https://user-images.githubusercontent.com/18205561/103267058-ea2ea600-49eb-11eb-8a0c-eb89a2f43890.gif)

**Comment by loveinsky100** [comment]
新增两个参数
${function_name} 获取函数名称
${date} 打印当前日志
