### ISSUE TITLE
// Package ${package_name} ${todo}.这个模板生成结果不符

### ISSUE THREAD

**Issue by twgh** [loveinsky100/goanno#30]
包注释模板:
`// Package ${package_name} ${todo}.`

生成结果:
`// Package ${package_name} .`

**Comment by loveinsky100** [comment]
邮件已收到。徐

**Comment by twgh** [comment]
就是包名没有生成

**Comment by loveinsky100** [comment]
已修复，下个版本支持

**Comment by loveinsky100** [comment]
https://github.com/loveinsky100/goanno/commit/16b803047f48f468e5b18dc42e667f72a891f69b
