### ISSUE TITLE
在IntelliJ IDEA里怎么设置呢

### ISSUE THREAD

**Issue by 1121076248** [loveinsky100/goanno#34]
找了好久都没找到

**Comment by Sup-W** [comment]
直接在栏目里面有一个Tools，下面有配置
![image](https://user-images.githubusercontent.com/18663072/162385037-fe4eeb7c-dfe4-4beb-b46f-991d5c86d0fa.png)

**Comment by 1121076248** [comment]
IntelliJ IDEA里没有Tools栏，goland有

**Comment by loveinsky100** [comment]
![image](https://user-images.githubusercontent.com/18205561/186312095-ebae2749-0c0f-464f-8ed2-0125aef2f5c7.png)
也是有的，可以看下是否在idea里安装了插件，goland和idea的插件都要单独安装
