### ISSUE TITLE
再 goland 中 在函数可以导出的情况下生成的注释 因为有2个空格而提示

### ISSUE THREAD

**Issue by puzzle9** [loveinsky100/goanno#36]
![image](https://user-images.githubusercontent.com/13518196/168742377-9160708d-a4e3-4b40-a809-8d09d1782c50.png)

当然 这样是这样的了
![image](https://user-images.githubusercontent.com/13518196/168742656-887cd4d6-8794-4fa7-83b0-b0d4c5611e3d.png)

**Comment by loveinsky100** [comment]
邮件已收到。徐

**Comment by loveinsky100** [comment]
可以直接调整模版
//
// ${function_name}
//  @Description: ${todo}
//  @receiver ${receiver}
//  @param ${params}
//  @return ${return_types}
//

**Comment by loveinsky100** [comment]
![image](https://user-images.githubusercontent.com/18205561/186332543-3fb9855a-e47d-4d6a-9b53-a6ebec3737c5.png)
![image](https://user-images.githubusercontent.com/18205561/186332562-45cc23ee-ab9f-4b0f-aeb5-2baad074d5de.png)
