### ISSUE TITLE
覆盖现有注释

### ISSUE THREAD

**Issue by liu-junyong** [loveinsky100/goanno#4]
跟现有注释合并
比如现在已经有一些注释了。
应该读取现有的注释，然后合并进去

**Comment by loveinsky100** [comment]
这个功能可以有，会加到开发计划中，预计本周或下周添加这个功能



发自我的iPhone


------------------ 原始邮件 ------------------

**Comment by loveinsky100** [comment]
目前已经调整了整个生成逻辑，原先采用map存储按照上下文形式进行生成，现在已经结构化下来，预计下个迭代就能支持

**Comment by loveinsky100** [comment]
已支持
