### ISSUE TITLE
GO语言的${function_name}无法获取

### ISSUE THREAD

**Issue by 19520** [loveinsky100/goanno#5]
设置格式如下：
// ${function_name}: ${todo}
//   receiver: ${receiver}
//   param: ${params}
//   return: ${return_types}

在goland中依然显示${function_name}，而不是函数名称。

**Comment by loveinsky100** [comment]
试了下，一行添加多个 变量 存在点问题，你可以先

**Comment by 19520** [comment]
好的感谢！

**Comment by loveinsky100** [comment]
https://github.com/loveinsky100/goanno/releases/tag/2.1.0
新版本已经修复，可以直接从release中下载，jetbrains正在审核，预计2天时间可以从插件市场下载
