### ISSUE TITLE
添加一下自定义快捷键吧

### ISSUE THREAD

**Issue by zhangxin-le** [loveinsky100/goanno#6]
添加一下自定义快捷键吧，这个快捷键不是很好用。
功能很赞，刚好用的到

**Comment by loveinsky100** [comment]
这个得看下插件开发的文档，不确定是否有这功能，你能提供下哪些快捷键比较合适吗，我可以先多加几种快捷键进去。

**Comment by zhangxin-le** [comment]
/* 然后自动补全？

**Comment by loveinsky100** [comment]
这个会和系统定义的冲突，等放假我再看下怎么加下，最近这几天事情比较多，暂时没时间看



发自我的iPhone


------------------ 原始邮件 ------------------

**Comment by zhangxin-le** [comment]
ok

**Comment by loveinsky100** [comment]
https://github.com/loveinsky100/goanno/releases/tag/2.1.0
新版本已经支持，可以直接从release中下载，jetbrains正在审核，预计2天时间可以从插件市场下载

**Comment by zhangxin-le** [comment]
thanks
