### ISSUE TITLE
生成的时候可以有类型吗?

### ISSUE THREAD

**Issue by liuaiyuan** [loveinsky100/goanno#7]
例如:
```go
func (arg1 string,arg2 int64)(value string,err error){}
```

需要一个 `param_types` 和 `return_param`

**Comment by loveinsky100** [comment]
现在没有，不过正在开发中。新的逻辑会支持更多的 变量 信息，包括名称和类型

**Comment by loveinsky100** [comment]
https://github.com/loveinsky100/goanno/releases/tag/2.1.0
新版本已经支持，可以直接从release中下载，jetbrains正在审核，预计2天时间可以从插件市场下载
